spring:
  application:
    name: springboot3-shardingsphere-demo

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yml

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3306/db_shardingsphere_demo_01?characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 1234